global:
  runner:
    containers:
      - image: hungpham10/algorithm:latest
    
tasks:  
  perform-etl-for-every-stocks:
    steps:
      - run: dockerize -wait tcp://localhost:5432
      - run: ls -al .
