global:
  runner:
    containers:
      - image: hungpham10/algorithm:latest
    
tasks:  
  perform_stock_pricing_etl: ## task name
    steps:
      - run: dockerize -wait tcp://localhost:5432
      - run: ls -al .
