version: 2.1
jobs:
  build-trend-following-models:
    docker:
      - image: ghcr.io/hungpham10/algorithm:latest
    environment:
      ENVIRONMENT: "prod"
      DISABLE_AUTO_INIT_DATABASE: "true"
    steps:
      - run:
          name: Run command to build model
          command: |
            /app/endpoint.sh /app/aio /sql

workflows:
  build-models:
    jobs:
      - build-trend-following-models